FF_CONFIGURE="--enable-gpl --enable-nonfree --enable-version3 --disable-debug --disable-shared --enable-static"
FF_CFLAGS=""
FF_CXXFLAGS=""
FF_LDFLAGS=""
GIT_BRANCH="master"
LICENSE_FILE="COPYING.GPLv3"
